apiVersion: apps/v1
kind: Deployment
metadata:
  name: ujik89
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ujik89
  template:
    metadata:
      labels:
        app: ujik89
    spec:
      containers:
      - image: okteto.dev/ujik89:latest
        name: ujik89
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "893be8ca-0a66-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vl5t6"
        - name: Vmess_UUID
          value: "893be8ca-0a66-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm673"
        - name: Share_Path
          value: "/v2link"
