apiVersion: v1
kind: Service
metadata:
  name: ujik89
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ujik89"
    port: 8080
  selector:
    app: ujik89
